config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('midterm/', include('midterm.urls')),
    path('admin/', admin.site.urls),
]

midterm/urls.py
from django.urls import path
from . import views

app_name = 'midterm'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

midterm/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model) :
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self) :
        return self.question_text

    def was_published_recently(self) :
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model) :
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) :
        return self.choice_text

midterm/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

# Create your views here.
class IndexView(generic.ListView) :
    template_name = 'midterm/index.html'
    context_object_name = 'oldest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('pub_date')[:5]

class DetailView(generic.DetailView) :
    model = Question
    template_name = 'midterm/detail.html'

class ResultsView(generic.DetailView) :
    model = Question
    template_name = 'midterm/results.html'

def vote(request, question_id) :
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'midterm/detail.html',
                      {'question': question, 'error_message': "You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('midterm:results', args=(question_id,)))

midterm/templates/midterm/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'midterm/style.css' %}">
</head>
<body>
<h2>{{question.question_text}}</h2>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}

<form action="{% url 'midterm:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <br>
    <input type="submit" value="vote">
    &nbsp;or&nbsp;&nbsp;<a href="{% url 'midterm:index' %}">Back to First</a>
</form>
</body>
</html>

midterm/templates/midterm/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'midterm/style.css' %}">
</head>
<body>
<h1>Welcom!</h1>
<h4>&nbsp;Please select your answer following the question below.</h4>
{% if oldest_question_list %}
    <ul>
        {% for question in oldest_question_list %}
            <li><a href="{% url 'midterm:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No midterm is available.</p>
{% endif %}
</body>
</html>

midterm/templates/midterm/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'midterm/style.css' %}">
</head>
<body>
<h2>{{question.question_text}}</h2>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'midterm:detail' question.id %}">Vote Again?</a>
&nbsp;or&nbsp;&nbsp;<a href="{% url 'midterm:index' %}">Back to First</a>
</body>
</html>